# Generated by Django 2.2.3 on 2019-10-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок EN')),
                ('title_jp', models.CharField(max_length=200, verbose_name='Заголовок JP')),
                ('evolution_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='pokemon_entities.Pokemon', verbose_name='Эволюционирует от')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Появится')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Исчезнет')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('attack', models.IntegerField(blank=True, null=True, verbose_name='Атака')),
                ('protection', models.IntegerField(blank=True, null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
